In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from datetime import date
from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from torchvision import datasets, transforms

import copy
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import plotly.express as px
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import tqdm


In [ ]:
data_path = '/content/drive/MyDrive/0_318lab/ML/NewJChem2021_45_9427/inputData.xlsx'

pd_read = pd.read_excel(data_path)
x_np_array = np.array([])
y_np_array = np.array([])
pd_read_keys = pd_read.keys()
len_pd_read_keys = len(pd_read.keys())
for i in range(len_pd_read_keys):
    if 0 < i and i < 7:
        x_np_array = np.append(x_np_array, pd_read[ pd_read_keys[i] ])
    if i == 7:
        y_np_array = np.append(y_np_array, pd_read[ pd_read_keys[i] ])
x_np_array = x_np_array.reshape(6, 136).T


In [ ]:
found_duple = np.array([])
len_y_np_array = len(y_np_array)
for i in range(len_y_np_array):
    duple = np.where(np.all(x_np_array == x_np_array[i], axis=1))
    np.append( found_duple, duple )
    print(duple)

(array([0]),)
(array([1]),)
(array([2]),)
(array([3]),)
(array([4]),)
(array([5]),)
(array([6]),)
(array([7]),)
(array([8]),)
(array([9]),)
(array([10]),)
(array([11]),)
(array([12]),)
(array([13]),)
(array([14]),)
(array([15]),)
(array([16]),)
(array([17]),)
(array([18]),)
(array([19, 20]),)
(array([19, 20]),)
(array([21]),)
(array([22]),)
(array([23]),)
(array([24]),)
(array([25, 26, 27, 28]),)
(array([25, 26, 27, 28]),)
(array([25, 26, 27, 28]),)
(array([25, 26, 27, 28]),)
(array([29, 30]),)
(array([29, 30]),)
(array([31]),)
(array([32]),)
(array([33]),)
(array([34]),)
(array([35]),)
(array([36]),)
(array([37]),)
(array([38, 39]),)
(array([38, 39]),)
(array([40]),)
(array([41, 42]),)
(array([41, 42]),)
(array([43, 44, 45, 46]),)
(array([43, 44, 45, 46]),)
(array([43, 44, 45, 46]),)
(array([43, 44, 45, 46]),)
(array([47, 48, 49]),)
(array([47, 48, 49]),)
(array([47, 48, 49]),)
(array([50]),)
(array([51, 52]),)
(array([51, 52]),)
(array([53]),)
(array([54]),)
(array([55]),)
(array([56

In [ ]:
found_duple

array([], dtype=float64)

In [ ]:
 np.where(np.all(x_np_array == x_np_array[0], axis=1))

(array([0]),)

In [ ]:
 np.where(np.all(x_np_array == x_np_array[3], axis=1))

(array([3]),)